# Rename the project and update the description for your project
name: scora
description: "PrÉ™dict"
publish_to: "none"
version: 0.2.0+2

# Update the SDK version to the latest stable version
environment:
  sdk: ">=3.5.0 <4.0.0"

analyzer:
  plugins:
    - custom_lint
# Core Dependencies: (add/update using pubspec assist)
#
# hooks_riverpod,flutter_hooks,go_router,responsive_framework,intl,animations,json_annotation,freezed_annotation,http,shared_preferences,vector_graphics,gap,dartx
#
dependencies:
  animations: ^2.0.11
  another_flushbar: ^1.12.30
  dartx: ^1.2.0
  date_picker_timeline: ^1.2.6
  device_info_plus: ^10.1.2
  easy_date_timeline: ^1.1.3
  exposed:
    git:
      url: https://github.com/Hasuki69/exposed.git
      ref: main
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.2.3
  hooks_riverpod: ^2.5.1
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pinput: ^5.0.0
  rename: ^3.0.2
  responsive_framework: ^1.4.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.3
  shared_preferences: ^2.3.2
  vector_graphics: ^1.1.11+1

# Core Dev Dependencies: (add/update using pubspec assist)
#
# build_runner,custom_lint,flutter_lints,freezed,json_serializable,riverpod_lint
#
dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.13
  vector_graphics_compiler: ^1.1.11+1

# Assets and Fonts
# Modify the assets and fonts section to match your project's assets and fonts
#
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/svgs/
    - assets/icons/
    - .env
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"