const List<Map<String, String>> countriesData = [
  {"countryId": "1", "countryName": "Afghanistan"},
  {"countryId": "2", "countryName": "Albania"},
  {"countryId": "3", "countryName": "Algeria"},
  {"countryId": "4", "countryName": "American Samoa"},
  {"countryId": "5", "countryName": "Andorra"},
  {"countryId": "6", "countryName": "Angola"},
  {"countryId": "7", "countryName": "Anguilla"},
  {"countryId": "8", "countryName": "Antarctica"},
  {"countryId": "9", "countryName": "Antigua and Barbuda"},
  {"countryId": "10", "countryName": "Argentina"},
  {"countryId": "11", "countryName": "Armenia"},
  {"countryId": "12", "countryName": "Aruba"},
  {"countryId": "13", "countryName": "Australia"},
  {"countryId": "14", "countryName": "Austria"},
  {"countryId": "15", "countryName": "Azerbaijan"},
  {"countryId": "16", "countryName": "Bahamas"},
  {"countryId": "17", "countryName": "Bahrain"},
  {"countryId": "18", "countryName": "Bangladesh"},
  {"countryId": "19", "countryName": "Barbados"},
  {"countryId": "20", "countryName": "Belarus"},
  {"countryId": "21", "countryName": "Belgium"},
  {"countryId": "22", "countryName": "Belize"},
  {"countryId": "23", "countryName": "Benin"},
  {"countryId": "24", "countryName": "Bermuda"},
  {"countryId": "25", "countryName": "Bhutan"},
  {"countryId": "26", "countryName": "Bosnia and Herzegovina"},
  {"countryId": "27", "countryName": "Botswana"},
  {"countryId": "28", "countryName": "Bouvet Island"},
  {"countryId": "29", "countryName": "Brazil"},
  {"countryId": "30", "countryName": "British Indian Ocean Territory"},
  {"countryId": "31", "countryName": "Brunei Darussalam"},
  {"countryId": "32", "countryName": "Bulgaria"},
  {"countryId": "33", "countryName": "Burkina Faso"},
  {"countryId": "34", "countryName": "Burundi"},
  {"countryId": "35", "countryName": "Cambodia"},
  {"countryId": "36", "countryName": "Cameroon"},
  {"countryId": "37", "countryName": "Canada"},
  {"countryId": "38", "countryName": "Cape Verde"},
  {"countryId": "39", "countryName": "Cayman Islands"},
  {"countryId": "40", "countryName": "Central African Republic"},
  {"countryId": "41", "countryName": "Chad"},
  {"countryId": "42", "countryName": "Chile"},
  {"countryId": "43", "countryName": "China"},
  {"countryId": "44", "countryName": "Christmas Island"},
  {"countryId": "45", "countryName": "Cocos (Keeling) Islands"},
  {"countryId": "46", "countryName": "Colombia"},
  {"countryId": "47", "countryName": "Comoros"},
  {"countryId": "48", "countryName": "Congo"},
  {"countryId": "49", "countryName": "Cook Islands"},
  {"countryId": "50", "countryName": "Costa Rica"},
  {"countryId": "51", "countryName": "Croatia"},
  {"countryId": "52", "countryName": "Cuba"},
  {"countryId": "53", "countryName": "Cyprus"},
  {"countryId": "54", "countryName": "Czech Republic"},
  {"countryId": "55", "countryName": "Denmark"},
  {"countryId": "56", "countryName": "Djibouti"},
  {"countryId": "57", "countryName": "Dominica"},
  {"countryId": "58", "countryName": "Dominican Republic"},
  {"countryId": "59", "countryName": "Ecuador"},
  {"countryId": "60", "countryName": "Egypt"},
  {"countryId": "61", "countryName": "El Salvador"},
  {"countryId": "62", "countryName": "Equatorial Guinea"},
  {"countryId": "63", "countryName": "Eritrea"},
  {"countryId": "64", "countryName": "Estonia"},
  {"countryId": "65", "countryName": "Ethiopia"},
  {"countryId": "66", "countryName": "Falkland Islands (Malvinas)"},
  {"countryId": "67", "countryName": "Faroe Islands"},
  {"countryId": "68", "countryName": "Fiji"},
  {"countryId": "69", "countryName": "Finland"},
  {"countryId": "70", "countryName": "France"},
  {"countryId": "71", "countryName": "French Guiana"},
  {"countryId": "72", "countryName": "French Polynesia"},
  {"countryId": "73", "countryName": "French Southern Territories"},
  {"countryId": "74", "countryName": "Gabon"},
  {"countryId": "75", "countryName": "Gambia"},
  {"countryId": "76", "countryName": "Georgia"},
  {"countryId": "77", "countryName": "Germany"},
  {"countryId": "78", "countryName": "Ghana"},
  {"countryId": "79", "countryName": "Gibraltar"},
  {"countryId": "80", "countryName": "Greece"},
  {"countryId": "81", "countryName": "Greenland"},
  {"countryId": "82", "countryName": "Grenada"},
  {"countryId": "83", "countryName": "Guadeloupe"},
  {"countryId": "84", "countryName": "Guam"},
  {"countryId": "85", "countryName": "Guatemala"},
  {"countryId": "86", "countryName": "Guernsey"},
  {"countryId": "87", "countryName": "Guinea"},
  {"countryId": "88", "countryName": "Guinea-Bissau"},
  {"countryId": "89", "countryName": "Guyana"},
  {"countryId": "90", "countryName": "Haiti"},
  {"countryId": "91", "countryName": "Heard Island and McDonald Islands"},
  {"countryId": "92", "countryName": "Holy See (Vatican City State)"},
  {"countryId": "93", "countryName": "Honduras"},
  {"countryId": "94", "countryName": "Hong Kong"},
  {"countryId": "95", "countryName": "Hungary"},
  {"countryId": "96", "countryName": "Iceland"},
  {"countryId": "97", "countryName": "India"},
  {"countryId": "98", "countryName": "Indonesia"},
  {"countryId": "99", "countryName": "Iran"},
  {"countryId": "100", "countryName": "Iraq"},
  {"countryId": "101", "countryName": "Ireland"},
  {"countryId": "102", "countryName": "Isle of Man"},
  {"countryId": "103", "countryName": "Israel"},
  {"countryId": "104", "countryName": "Italy"},
  {"countryId": "105", "countryName": "Jamaica"},
  {"countryId": "106", "countryName": "Japan"},
  {"countryId": "107", "countryName": "Jersey"},
  {"countryId": "108", "countryName": "Jordan"},
  {"countryId": "109", "countryName": "Kazakhstan"},
  {"countryId": "110", "countryName": "Kenya"},
  {"countryId": "111", "countryName": "Kiribati"},
  {"countryId": "112", "countryName": "Kuwait"},
  {"countryId": "113", "countryName": "Kyrgyzstan"},
  {"countryId": "114", "countryName": "Lao Peoples Democratic Republic"},
  {"countryId": "115", "countryName": "Latvia"},
  {"countryId": "116", "countryName": "Lebanon"},
  {"countryId": "117", "countryName": "Lesotho"},
  {"countryId": "118", "countryName": "Liberia"},
  {"countryId": "119", "countryName": "Libya"},
  {"countryId": "120", "countryName": "Liechtenstein"},
  {"countryId": "121", "countryName": "Lithuania"},
  {"countryId": "122", "countryName": "Luxembourg"},
  {"countryId": "123", "countryName": "Macao"},
  {"countryId": "124", "countryName": "Madagascar"},
  {"countryId": "125", "countryName": "Malawi"},
  {"countryId": "126", "countryName": "Malaysia"},
  {"countryId": "127", "countryName": "Maldives"},
  {"countryId": "128", "countryName": "Mali"},
  {"countryId": "129", "countryName": "Malta"},
  {"countryId": "130", "countryName": "Marshall Islands"},
  {"countryId": "131", "countryName": "Mauritania"},
  {"countryId": "132", "countryName": "Mauritius"},
  {"countryId": "133", "countryName": "Mayotte"},
  {"countryId": "134", "countryName": "Mexico"},
  {"countryId": "135", "countryName": "Micronesia"},
  {"countryId": "136", "countryName": "Moldova"},
  {"countryId": "137", "countryName": "Monaco"},
  {"countryId": "138", "countryName": "Mongolia"},
  {"countryId": "139", "countryName": "Montenegro"},
  {"countryId": "140", "countryName": "Montserrat"},
  {"countryId": "141", "countryName": "Morocco"},
  {"countryId": "142", "countryName": "Mozambique"},
  {"countryId": "143", "countryName": "Myanmar"},
  {"countryId": "144", "countryName": "Namibia"},
  {"countryId": "145", "countryName": "Nauru"},
  {"countryId": "146", "countryName": "Nepal"},
  {"countryId": "147", "countryName": "Netherlands"},
  {"countryId": "148", "countryName": "New Caledonia"},
  {"countryId": "149", "countryName": "New Zealand"},
  {"countryId": "150", "countryName": "Nicaragua"},
  {"countryId": "151", "countryName": "Niger"},
  {"countryId": "152", "countryName": "Nigeria"},
  {"countryId": "153", "countryName": "Niue"},
  {"countryId": "154", "countryName": "Norfolk Island"},
  {"countryId": "155", "countryName": "North Korea"},
  {"countryId": "156", "countryName": "Northern Mariana Islands"},
  {"countryId": "157", "countryName": "Norway"},
  {"countryId": "158", "countryName": "Oman"},
  {"countryId": "159", "countryName": "Pakistan"},
  {"countryId": "160", "countryName": "Palau"},
  {"countryId": "161", "countryName": "Palestine"},
  {"countryId": "162", "countryName": "Panama"},
  {"countryId": "163", "countryName": "Papua New Guinea"},
  {"countryId": "164", "countryName": "Paraguay"},
  {"countryId": "165", "countryName": "Peru"},
  {"countryId": "166", "countryName": "Philippines"},
  {"countryId": "167", "countryName": "Pitcairn"},
  {"countryId": "168", "countryName": "Poland"},
  {"countryId": "169", "countryName": "Portugal"},
  {"countryId": "170", "countryName": "Puerto Rico"},
  {"countryId": "171", "countryName": "Qatar"},
  {"countryId": "172", "countryName": "Réunion"},
  {"countryId": "173", "countryName": "Romania"},
  {"countryId": "174", "countryName": "Russian Federation"},
  {"countryId": "175", "countryName": "Rwanda"},
  {"countryId": "176", "countryName": "Saint Barthelemy"},
  {"countryId": "177", "countryName": "Saint Helena"},
  {"countryId": "178", "countryName": "Saint Kitts and Nevis"},
  {"countryId": "179", "countryName": "Saint Lucia"},
  {"countryId": "180", "countryName": "Saint Martin"},
  {"countryId": "181", "countryName": "Saint Pierre and Miquelon"},
  {"countryId": "182", "countryName": "Saint Vincent and the Grenadines"},
  {"countryId": "183", "countryName": "Samoa"},
  {"countryId": "184", "countryName": "San Marino"},
  {"countryId": "185", "countryName": "Sao Tome and Principe"},
  {"countryId": "186", "countryName": "Saudi Arabia"},
  {"countryId": "187", "countryName": "Senegal"},
  {"countryId": "188", "countryName": "Serbia"},
  {"countryId": "189", "countryName": "Seychelles"},
  {"countryId": "190", "countryName": "Sierra Leone"},
  {"countryId": "191", "countryName": "Singapore"},
  {"countryId": "192", "countryName": "Sint Maarten"},
  {"countryId": "193", "countryName": "Slovakia"},
  {"countryId": "194", "countryName": "Slovenia"},
  {"countryId": "195", "countryName": "Solomon Islands"},
  {"countryId": "196", "countryName": "Somalia"},
  {"countryId": "197", "countryName": "South Africa"},
  {"countryId": "198", "countryName": "South Georgia and the South Sandwich Islands"},
  {"countryId": "199", "countryName": "South Sudan"},
  {"countryId": "200", "countryName": "Spain"},
  {"countryId": "201", "countryName": "Sri Lanka"},
  {"countryId": "202", "countryName": "Sudan"},
  {"countryId": "203", "countryName": "Suriname"},
  {"countryId": "204", "countryName": "Svalbard and Jan Mayen"},
  {"countryId": "205", "countryName": "Sweden"},
  {"countryId": "206", "countryName": "Switzerland"},
  {"countryId": "207", "countryName": "Syrian Arab Republic"},
  {"countryId": "208", "countryName": "Taiwan"},
  {"countryId": "209", "countryName": "Tajikistan"},
  {"countryId": "210", "countryName": "Tanzania"},
  {"countryId": "211", "countryName": "Thailand"},
  {"countryId": "212", "countryName": "Timor-Leste"},
  {"countryId": "213", "countryName": "Togo"},
  {"countryId": "214", "countryName": "Tokelau"},
  {"countryId": "215", "countryName": "Tonga"},
  {"countryId": "216", "countryName": "Trinidad and Tobago"},
  {"countryId": "217", "countryName": "Tunisia"},
  {"countryId": "218", "countryName": "Turkey"},
  {"countryId": "219", "countryName": "Turkmenistan"},
  {"countryId": "220", "countryName": "Tuvalu"},
  {"countryId": "221", "countryName": "Uganda"},
  {"countryId": "222", "countryName": "Ukraine"},
  {"countryId": "223", "countryName": "United Arab Emirates"},
  {"countryId": "224", "countryName": "United Kingdom"},
  {"countryId": "225", "countryName": "United States"},
  {"countryId": "226", "countryName": "Uruguay"},
  {"countryId": "227", "countryName": "Uzbekistan"},
  {"countryId": "228", "countryName": "Vanuatu"},
  {"countryId": "229", "countryName": "Venezuela"},
  {"countryId": "230", "countryName": "Viet Nam"},
  {"countryId": "231", "countryName": "Western Sahara"},
  {"countryId": "232", "countryName": "Yemen"},
  {"countryId": "233", "countryName": "Zambia"},
  {"countryId": "234", "countryName": "Zimbabwe"},
];
